// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CawoodClinic.Shared.Enums;
using System;
using System.Collections.Generic;

namespace CawoodClinic.Blazor.Auth.Models;

public partial class AspNetUserDevice
{
    public Guid Id { get; set; }

    public string UserId { get; set; }

    public Guid DeviceId { get; set; }

    public string RefreshToken { get; set; }

    public DateTime RefreshTokenExpiryTime { get; set; }

    public string Idiom { get; set; }

    public bool IsPrimaryDevice { get; set; }    

    public LogEventLevel LogLevel { get; set; } = LogEventLevel.Error;
}