// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using System.Reflection.Emit;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using CawoodClinic.Blazor.Auth.Models;

namespace CawoodClinic.Blazor.Models;

public class AuthDbContext : IdentityDbContext<IdentityUser>
{
    public AuthDbContext(DbContextOptions<AuthDbContext> options) : base(options)
    {
    }

    public virtual DbSet<AspNetUserDevice> AspNetUserDevices { get; set; }


    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<AspNetUserDevice>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.RefreshToken)
                .IsRequired()
                .HasMaxLength(450);
            entity.Property(e => e.RefreshTokenExpiryTime).HasColumnType("datetime");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(450);
        });
        base.OnModelCreating(builder);

    }
}