// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CawoodClinic.Blazor.Data;

public partial class Dbsync
{
    public int Id { get; set; }

    public string NameSpace { get; set; }

    public string TableName { get; set; }

    public long LastSyncVersion { get; set; }

    public DateTime LastSyncDate { get; set; }

    public int SyncOrder { get; set; }

    public int RetentionDays { get; set; }

    public int SyncDirection { get; set; }

    public bool IsDeleted { get; set; }

    public Guid? LastUpdatedDeviceId { get; set; }
}