// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace CawoodClinic.Maui.Data.Models;

public partial class Appointment
{
    public Guid Id { get; set; }

    public DateTime DateOfAppointment { get; set; }

    public string AppointmentReason { get; set; }

    public Guid AppointmentStatusId { get; set; }

    public string AppointmentNotes { get; set; }

    public Guid PatientId { get; set; }

    public string UserId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual AppointmentStatus AppointmentStatus { get; set; }

    public virtual Patient Patient { get; set; }

}