// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CawoodClinic.Maui.Data.Models;

public partial class Patient
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string IdNumber { get; set; }

    public string ContactNumber { get; set; }

    public string EmailAddress { get; set; }

    public string PhysicalAddress { get; set; }

    public Guid? RegionId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<Measurement> Measurements { get; set; } = new List<Measurement>();

    public virtual Region Region { get; set; }
}