// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CawoodClinic.Blazor.Data;

public partial class MeasurementType
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string FormatOfMeasurement { get; set; }

    public bool IsDeleted { get; set; }

    public string DataTypeOfMeasurement { get; set; }

    public virtual ICollection<Measurement> Measurements { get; set; } = new List<Measurement>();
}